version: '3'

services:
  mysql-container:
    image: mysql:latest
   # environment:
   #  - MYSQL_ROOT_PASSWORD=root123
   #   - MYSQL_DATABASE=db_localteste
   #   - MYSQL_USER=jorge
   #   - MYSQL_PASSWORD=Jorge_123
    volumes:
      - /data/mysql
  projeto2:
    image: projeto2

    #build:
    #  context: ./
    #  dockerfile: Dockerfile
    #depends_on:
    #  - mysql-docker-container
    ports:
      - 8087:8080
    volumes:
      - /data/spring-boot-app
